### ISSUE TITLE
another issue with multiple profiles

### ISSUE THREAD

**Issue by flik** [facebook/php-webdriver#542] opened 2018-03-13 03:54 UTC
### What are you trying to achieve? (Expected behavior)
running a selenium test

### What do you get instead? (Actual behavior)
```bash
$ composer require facebook/webdriver
Using version ^1.5 for facebook/webdriver
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing symfony/process (v3.4.6): Loading from cache
  - Installing facebook/webdriver (1.5.0): Downloading (100%)
Writing lock file
Generating autoload files

feb2018@adminxA MINGW32 /d/xampp/htdocs/automation/selenium
$ php example.php
PHP Fatal error:  Uncaught Facebook\WebDriver\Exception\UnknownServerException:
Profile has been set on both the capabilities and these options, but they're dif
ferent. Unable to determine which one you want to use. in D:\xampp\htdocs\automa
tion\selenium\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:114

Stack trace:
#0 D:\xampp\htdocs\automation\selenium\vendor\facebook\webdriver\lib\Remote\Http
CommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throw
Exception(13, 'Profile has bee...', Array)
#1 D:\xampp\htdocs\automation\selenium\vendor\facebook\webdriver\lib\Remote\Remo
teWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Obj
ect(Facebook\WebDriver\Remote\WebDriverCommand))
#2 D:\xampp\htdocs\automation\selenium\example.php(16): Facebook\WebDriver\Remot
e\RemoteWebDriver::create('http://127.0.0....', Object(Facebook\WebDriver\Remote
\DesiredCapabilities), 5000)
#3 {main}
  thrown in D:\xampp\htdocs\automation\selenium\vendor\facebook\webdriver\lib\Ex
ception\WebDriverException.php on line 114

Fatal error: Uncaught Facebook\WebDriver\Exception\UnknownServerException: Profi
le has been set on both the capabilities and these options, but they're differen
t. Unable to determine which one you want to use. in D:\xampp\htdocs\automation\
selenium\vendor\facebook\webdriver\lib\Exception\WebDriverException.php:114
Stack trace:
#0 D:\xampp\htdocs\automation\selenium\vendor\facebook\webdriver\lib\Remote\Http
CommandExecutor.php(320): Facebook\WebDriver\Exception\WebDriverException::throw
Exception(13, 'Profile has bee...', Array)
#1 D:\xampp\htdocs\automation\selenium\vendor\facebook\webdriver\lib\Remote\Remo
teWebDriver.php(126): Facebook\WebDriver\Remote\HttpCommandExecutor->execute(Obj
ect(Facebook\WebDriver\Remote\WebDriverCommand))
#2 D:\xampp\htdocs\automation\selenium\example.php(16): Facebook\WebDriver\Remot
e\RemoteWebDriver::create('http://127.0.0....', Object(Facebook\WebDriver\Remote
\DesiredCapabilities), 5000)
#3 {main}
  thrown in D:\xampp\htdocs\automation\selenium\vendor\facebook\webdriver\lib\Ex
ception\WebDriverException.php on line 114


```

### How could the issue be reproduced? (Steps to reproduce)
run selenium server with: 
$ java -jar -Dwebdriver.gecko.driver=geckodriver32.exe selenium-server-standalon                       e-3.3.0.jar

then run in other terminal:
php example.php

```php
<?php
// An example of using php-webdriver.

namespace Facebook\WebDriver;

use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

require_once('vendor/autoload.php');

// start Firefox with 5 second timeout
$host = 'http://127.0.0.1:4444/wd/hub'; // this is the default

//Firefox setting
$capabilities = DesiredCapabilities::firefox(); 
$driver = RemoteWebDriver::create($host, $capabilities, 5000);


//Safari driver Settings
//$driver = RemoteWebDriver::create($host, DesiredCapabilities::safari());

//Crome driver Settings
//$driver = RemoteWebDriver::create($host, DesiredCapabilities::chrome());

// navigate to 'http://www.seleniumhq.org/'
$driver->get('http://www.seleniumhq.org/');

/* */
// adding cookie
$driver->manage()->deleteAllCookies();

$cookie = new Cookie('cookie_name', 'cookie_value');
$driver->manage()->addCookie($cookie);

$cookies = $driver->manage()->getCookies();
print_r($cookies);


// click the link 'About'
$link = $driver->findElement(
    WebDriverBy::id('menu_about')
);
$link->click();

// wait until the page is loaded
$driver->wait()->until(
    WebDriverExpectedCondition::titleContains('About')
);

// print the title of the current page
echo "The title is '" . $driver->getTitle() . "'\n";

// print the URI of the current page
echo "The current URI is '" . $driver->getCurrentURL() . "'\n";

// write 'php' in the search box
$driver->findElement(WebDriverBy::id('q'))
    ->sendKeys('php');

// submit the form
$driver->findElement(WebDriverBy::id('submit'))
    ->click(); // submit() does not work in Selenium 3 because of bug https://github.com/SeleniumHQ/selenium/issues/3398

// wait at most 10 seconds until at least one result is shown
$driver->wait(10)->until(
    WebDriverExpectedCondition::presenceOfAllElementsLocatedBy(
        WebDriverBy::className('gsc-result')
    )
);

// close the Firefox
$driver->quit();

```

### Details

* Php-webdriver version:  latest
* PHP version: 7.x
* Selenium server version: 3.3.0
* Operating system: windows 8.1
* Browser used + version:  firefox

**Comment by OndraM** [comment] 2018-03-13 16:23
Duplicate of https://github.com/facebook/php-webdriver/issues/432 .

**Closed by OndraM** 2018-03-13 16:23 UTC
