### ISSUE TITLE
arguments undefined in executeScript()

### ISSUE THREAD

**Issue by omeraslam-vteams** [facebook/php-webdriver#196] opened 2015-01-19 12:56 UTC
dont know if others are also having this problem but i am getting `undefined` for the arguments 
see below code 
`echo $myBrowserDriver->executeScript('return alert(arguments[0])',array('john','don'));`
please look into it 
regards,
Omer Aslam

**Comment by omeraslam-vteams** [comment] 2015-01-20 08:16
anybody tried it so far ? i am still getting the same `undefined` result 
regards,
Omer Aslam

**Comment by gabrielpreston** [comment] 2015-01-20 17:44
Looking at this very briefly, it looks like the arguments need to be provided in a key=>value pairing. Take a look at the prepareScriptArguments() function at line 234 of lib/remote/RemoteWebDriver.php. Someone else may be able to speak more to this.

**Comment by whhone** [comment] 2015-01-20 19:12
@omeraslam-vteams 

`echo $myBrowserDriver->executeScript('return alert(arguments[0])',array('john','don'));` looks good and it works on OSX/firefox.

What is the platform/browser you were using?

**Comment by omeraslam-vteams** [comment] 2015-01-21 09:39
@whhone well i am using with the following environment  

OS
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

Browser
Firefox version 35.0

Selenium Server 2.44.0

and this simple line is giving me the `undefined` in alert it was working before Last Thursday 15th Jan after i updated my copy via composer.dont know what happened my working tests started to fail.

@gabrielpreston no it's just checking if the `instance of webdriver` is passed via arguments array to the method in the `value` then gets the `ID` for that element else checks if it is an `array()` then call the method again passing the `value` as a parameter and if not then saves the `value` in the `$args array()`
regards,
Omer Aslam

**Comment by omeraslam-vteams** [comment] 2015-01-27 10:31
No response from anyone yet on this issue

**Comment by gfosco** [comment] 2015-05-12 23:52
Closing this as it doesn't appear to be widespread, and does not have a clear reproduction.  Since it was working for you and then stopped, and is working for others, I lean towards thinking this is a problem with your setup.  Thanks.

**Closed by gfosco** 2015-05-12 23:52 UTC
