### ISSUE TITLE
Not working with Selenium Standalone Containers (due to protocol changes with GeckoDriver) > 3.4

### ISSUE THREAD

**Issue by dlgoodchild** [facebook/php-webdriver#479] opened 2017-10-06 10:34 UTC
### What are you trying to achieve? (Expected behavior)
Trying to use the latest selenium standalone docker, e.g. `image: "selenium/standalone-firefox-debug:3.6.0-3.6.0-bromine`, or even `3.5.3-boron`.

### What do you get instead? (Actual behavior)
Exception after exception

### How could the issue be reproduced? (Steps to reproduce)
Using the docker instructions run a local standalone firefox selenium container. Try to use this library and you'll not get very far.
Revert to an older image (e.g. working = `image: "selenium/standalone-firefox-debug:3.4.0-dysprosium"`), will work perfectly well with this library.

### Details
* Php-webdriver version: 1.4.1 (latest at time of writing).
* PHP version: 7.1.9
* Selenium server version: anything > 3.4
* Operating system: whatever the docker container is based on
* Browser used + version: Firefox

**Comment by paulbriton** [comment] 2017-10-11 08:59
The issue came more from the GeckoDriver than from Selenium itself. There is a new Webdriver Specification which is implemented in the GeckoDriver and this project still uses old Selenium JsonWireProtocol. 
There are plans for supporting the spec as mentioned here (#469). 
By then, we will have problems supporting new Selenium releases.

**Comment by dlgoodchild** [comment] 2017-10-11 09:10
Yeah, I've recently dropped using this library in favour of the Ruby and Python bindings as they seem to work using the new W3C WebDriver protocol and also fully support actions too. On top of that it means we can use the latest selenium standalone containers. Looks like a serious work to upgrade the php-webdriver though :/

**Comment by dlgoodchild** [comment] 2017-10-11 09:11
Updated the title of this issue to reflect the actual issue more clearly.

**Comment by OndraM** [comment] 2017-10-11 09:20
Hi @dlgoodchild , thanks for the report. 

This is a known issue, caused by the fact that Selenium since version 3.5 do not translates to the W3C protocol by default, and firefox does only support the W3C protocol. The W3C protocol is not yet fully implemented in php-webdriver, so in meanwhile, you could either use Chrome (which works pretty well), or Selenium 3.4, or it is not a problem to disable the W3C protocol in Selenium (as mentioned in #469), using selenium option `-enablePassThrough false`. For docker, this would mean something like this:

`docker run -p 4444:4444 -p 5900:5900 -e SE_OPTS="-enablePassThrough false" selenium/standalone-firefox-debug:3.6`

(However, you will still face some issues, with `actions()` etc.)

Closing this, as this will be solved by #469 .

Thank you

**Closed by OndraM** 2017-10-11 09:20 UTC
