### ISSUE TITLE
 Illegal string offset 'ELEMENT'

### ISSUE THREAD

**Issue by hadouke** [facebook/php-webdriver#466] opened 2017-08-31 12:17 UTC
### What are you trying to achieve? (Expected behavior)
Interact with requested element on the page

### What do you get instead? (Actual behavior)
  [PHPUnit_Framework_Exception] Illegal string offset 'ELEMENT'

### How could the issue be reproduced? (Steps to reproduce)
This happens randomly while running tests with Codeception+PhantomJS 

By changing some code here: https://github.com/facebook/php-webdriver/blob/community/lib/Remote/RemoteWebDriver.php#L198  to this:
```
    $elements = [];
    foreach ($raw_elements as $raw_element) {
        if(is_string($raw_element)){
            die("Raw Element: $raw_element");
        }
        $elements[] = $this->newElement($raw_element['ELEMENT']);
    }

    return $elements;
```
will give us next result: 
`Raw Element: {"request":{"headers":{"Accept":"application/json","Content-Length":"40","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:4444"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"class name\",\"value\":\"loading\"}","url":"/elements","urlParsed":{"anchor":"","query":"","file":"elements","directory":"/","path":"/elements","relative":"/elements","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/elements","queryKey":{},"chunks":["elements"]},"urlOriginal":"/session/05a65dc0-662d-11e7-968f-5d27b83b5460/elements"}}`

**Comment by paulbriton** [comment] 2017-09-01 13:58
Might be a duplicate of #468

**Comment by OndraM** [comment] 2017-09-05 21:07
@paulbriton Not quite sure - the original report I found dates to June, before the Selenium 3.5 was out: http://phptest.club/t/phpunit-framework-exception-illegal-string-offset-element/1547

@hadouke Could you please provide some additional information? 
* Php-webdriver version: 
* PHP version: 
* Selenium server version: 
* Operating system: 
* Browser used + version: 

Thanks!

**Comment by hadouke** [comment] 2017-09-06 15:01
@OndraM 
Php-webdriver version: 1.4.1
PHP version:  7.0.22
Selenium server version: 3.5.3
Operating system: Windows 10
Browser used + version: PhantomJS 2.1.1

**Comment by OndraM** [comment] 2017-09-06 15:05
@hadouke Thanks, so it look like of dupe of #468 ... Could you try Selenium server version 3.4?

And BTW, PhantomJS in version 2 did never properly support Selenium (there is many bugs and unfinished features in the protocol implementation in phantom js), so the issue may be there as well. 

Also as PhantomJS is no longer developed and maintained, I suggest moving to to [headless Chromedriver](https://developers.google.com/web/updates/2017/04/headless-chrome) instead.

I guess there is nothing more we can do, sorry :-(.

**Closed by OndraM** 2017-09-06 15:05 UTC
Labels: needs more info

**Comment by JohnDeeBDD** [comment] 2019-09-25 19:22
This is NOT a PhantomJS issue. I'm getting it with Selenium and Chromedriver
