### ISSUE TITLE
Facebook\WebDriver\Exception\UnrecognizedExceptionException:invalid arguement    with jenkins

### ISSUE THREAD

**Issue by rahu923** [facebook/php-webdriver#715] opened 2019-12-18 08:03 UTC
### What are you trying to achieve? (Expected behavior)
php artisan dusk

### What do you get instead? (Actual behavior)
facebook/webdriver exception 

### How could the issue be reproduced? (Steps to reproduce)
command is workinf fine on centos vm itself but not working while using jenkins

```php
// You can insert your PHP code here (or remove this block if it is not relevant for the issue).
```

### Details

* Php-webdriver version: 
* PHP version: 
* Selenium server version: 
* Operating system: 
* Browser used + version:

**Comment by williamdes** [comment] 2019-12-18 08:13
Duplicate of #711

**Closed** 2019-12-18 14:20 UTC
