### ISSUE TITLE
W3C protocol support

### ISSUE THREAD

**Issue by matjanis** [facebook/php-webdriver#579] opened 2018-06-04 09:29 UTC
Hey, 
can we got some information about php-webdriver support for W3C protocol (release date to be specific)? It's hard to keep quality with more than a year old firefox version;) 
Thanks,
Mateusz

**Comment by rzeziol** [comment] 2018-06-07 14:06
+1

**Comment by gohelkiran** [comment] 2018-06-07 16:35
+1

**Comment by jmarkk** [comment] 2018-06-08 07:57
+1

**Comment by Mayers666** [comment] 2018-06-08 08:30
+1

**Comment by ericthefish** [comment] 2018-06-22 09:35
+1

**Comment by thejahweh** [comment] 2018-07-11 13:31
It just seems that this is never going to happen. Maybe they switched to something better? 😕 

Here is the existing issue about this problem: https://github.com/facebook/php-webdriver/issues/469

**Comment by leviv** [comment] 2018-08-03 21:19
+1

**Comment by OneEyedSpaceFish** [comment] 2018-08-13 11:25
+1

**Comment by OndraM** [comment] 2018-08-20 13:49
Hi, this is duplicate of #469 . I'm well aware of importance of the the issue, but there is no point in "+1" comments. All recommendations and possible workarounds are mentioned in the referenced issue. The library is still working properly even with latest Chrome, even without W3C protocol support. But the W3C support will definitely happen.

**Closed by OndraM** 2018-08-20 13:49 UTC
